name: Playwright CI - quick
 
on:
  workflow_dispatch:
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]
 
jobs:
  test:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code 
        uses: actions/checkout@v3
 
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
 
      - name: Install dependencies
        run: npm i
 
      - name: Install Playwright browsers + deps
        run: npx playwright install --with-deps
 
      - name: Run Playwright tests
        run: npx playwright test
 
      - name: Generate Allure report
        if: always()
        run: |
          npx allure generate reports/allure-results --clean -o reports/allure-report

      - name: Upload Allure HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report/

      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
 
 
